config/routes.rb
Spreedemo::Application.routes.draw do
  
  mount Spree::Core::Engine, :at => '/'
  
    root :to => 'products#index'

  resources :products

  match '/locale/set', :to => 'locale#set'

  resources :tax_categories

  resources :states, :only => :index

  match '/checkout/update/:state', :to => 'checkout#update', :as => :update_checkout
  match '/checkout/:state', :to => 'checkout#edit', :as => :checkout_state
  match '/checkout', :to => 'checkout#edit', :state => 'address', :as => :checkout

  resources :orders do
    post :populate, :on => :collection

    resources :line_items
    resources :creditcards
    resources :creditcard_payments

    resources :shipments do
      member do
        get :shipping_method
      end
    end

  end
  get '/cart', :to => 'orders#edit', :as => :cart
  put '/cart', :to => 'orders#update', :as => :update_cart
  put '/cart/empty', :to => 'orders#empty', :as => :empty_cart

  resources :shipments do
    member do
      get :shipping_method
      put :shipping_method
    end
  end

  match '/t/*id', :to => 'taxons#show', :as => :nested_taxons

  namespace :admin do
    resources :adjustments
    resources :zones
    resources :users do
      member do
        post :dismiss_banner
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories
    resources :configurations, :only => :index
    resources :products do
      resources :product_properties
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :option_types do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
          post :update_positions
        end
      end
      resources :taxons do
        member do
          get :select
          delete :remove
        end
        collection do
          post :available
          post :batch_select
          get  :selected
        end
      end
    end

    resources :option_types do
      collection do
        post :update_positions
      end
    end

    resources :properties do
      collection do
        get :filtered
      end
    end

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :inventory_settings
    resource :image_settings
    resources :google_analytics

    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
        get :history
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      member do
        get :get_children
      end

      resources :taxons
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :shipments
    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource  :tax_settings
    resources :calculators

    resources :trackers
    resources :payment_methods
    resources :mail_methods do
      member do
        post :testmail
      end
    end
  end

  match '/admin', :to => 'admin/orders#index', :as => :admin

  match '/content/cvv', :to => 'content#cvv'
  match '/content/*path', :to => 'content#show', :via => :get, :as => :content
  
  
  
  
  
  

end

app/models/spree/address.rb
module Spree
  class Address < ActiveRecord::Base
    belongs_to :country
    belongs_to :state

    has_many :shipments

    # validates :firstname, :lastname, :address1, :city, :zipcode, :country, :phone, :presence => true
    # validate :state_validate

    attr_accessible :firstname, :lastname, :address1, :address2,
                    :city, :zipcode, :country_id, :state_id,
                    :country, :state, :phone, :state_name,
                    :company, :alternative_phone,:full_name

    def full_name  
    [firstname, lastname].join(' ')  
  end  
  
  # Setter  
  def full_name=(name)  
    split = name.split(' ', 2)  
    self.firstname = split.first  
    self.lastname = split.last  
  end  

    # Disconnected since there's no code to display error messages yet OR matching client-side validation
    def phone_validate
      return if phone.blank?
      n_digits = phone.scan(/[0-9]/).size
      valid_chars = (phone =~ /^[-+()\/\s\d]+$/)
      errors.add :phone, :invalid unless (n_digits > 5 && valid_chars)
    end

    def self.default
      country = Spree::Country.find(Spree::Config[:default_country_id]) rescue Spree::Country.first
      new({:country => country}, :without_protection => true)
    end

    # Can modify an address if it's not been used in an order (but checkouts controller has finer control)
    # def editable?
    #   new_record? || (shipments.empty? && checkouts.empty?)
    # end

    def full_name
      "#{firstname} #{lastname}".strip
    end

    def state_text
      state.nil? ? state_name : (state.abbr.blank? ? state.name : state.abbr)
    end

    def zone
      (state && state.zone) || (country && country.zone)
    end

    def zones
      Zone.match(self)
    end

    def same_as?(other)
      return false if other.nil?
      attributes.except('id', 'updated_at', 'created_at') == other.attributes.except('id', 'updated_at', 'created_at')
    end

    alias same_as same_as?

    def to_s
      "#{full_name}: #{address1}"
    end

    def clone
      self.class.new(self.attributes.except('id', 'updated_at', 'created_at'))
    end

    def ==(other_address)
      self_attrs = self.attributes
      other_attrs = other_address.respond_to?(:attributes) ? other_address.attributes : {}

      [self_attrs, other_attrs].each { |attrs| attrs.except!('id', 'created_at', 'updated_at', 'order_id') }

      self_attrs == other_attrs
    end

    def empty?
      attributes.except('id', 'created_at', 'updated_at', 'order_id', 'country_id').all? { |_, v| v.nil? }
    end

    # Generates an ActiveMerchant compatible address hash
    def active_merchant_hash
      {
        :name => full_name,
        :address1 => address1,
        :address2 => address2,
        :city => city,
        :state => state_text,
        :zip => zipcode,
        :country => country.try(:iso),
        :phone => phone
      }
    end

    private

      def state_validate
        # Skip state validation without country (also required)
        # or when disabled by preference
        return if country.blank? || !Spree::Config[:address_requires_state]

        # ensure associated state belongs to country
        if state.present?
          if state.country == country
            self.state_name = nil #not required as we have a valid state and country combo
          else
            if state_name.present?
              self.state = nil
            else
              errors.add(:state, :invalid)
            end
          end
        end

        # ensure state_name belongs to country without states, or that it matches a predefined state name/abbr
        if state_name.present?
          if country.states.present?
            states = country.states.find_all_by_name_or_abbr(state_name)

            if states.size == 1
              self.state = states.first
              self.state_name = nil
            else
              errors.add(:state, :invalid)
            end
          end
        end

        # ensure at least one state field is populated
        errors.add :state, :blank if state.blank? && state_name.blank?
      end

  end
end

app/models/spree/current_order_decorator.rb
Spree::Core::CurrentOrder.module_eval do
  # Associate the new order with the currently authenticated user before saving
  def before_save_new_order
    @current_order.user ||= current_user
  end

  def after_save_new_order
    # make sure the user has permission to access the order (if they are a guest)
    return if current_user
    session[:access_token] = @current_order.token
  end
end

app/models/spree/image.rb
module Spree
  class Image < Asset
    validates_attachment_presence :attachment
    validate :no_attachment_errors

    attr_accessible :alt, :attachment, :position, :viewable_type, :viewable_id

    has_attached_file :attachment,
                      :styles => { :mini => '48x48>', :small => '100x100>', :product => '240x240>', :large => '600x600>' },
                      :default_style => :product,
                      :url => '/spree/products/:id/:style/:basename.:extension',
                      :path => ':rails_root/public/spree/products/:id/:style/:basename.:extension'
    # save the w,h of the original image (from which others can be calculated)
    # we need to look at the write-queue for images which have not been saved yet
    after_post_process :find_dimensions

    # Load user defined paperclip settings
    if Spree::Config[:use_s3]
      s3_creds = { :access_key_id => Spree::Config[:s3_access_key], :secret_access_key => Spree::Config[:s3_secret], :bucket => Spree::Config[:s3_bucket] }
      Spree::Image.attachment_definitions[:attachment][:storage] = :s3
      Spree::Image.attachment_definitions[:attachment][:s3_credentials] = s3_creds
      Spree::Image.attachment_definitions[:attachment][:s3_headers] = ActiveSupport::JSON.decode(Spree::Config[:s3_headers])
      Spree::Image.attachment_definitions[:attachment][:bucket] = Spree::Config[:s3_bucket]
    end

    Spree::Image.attachment_definitions[:attachment][:styles] = { :mini => '48x48', :small => '100x100', :product => '240x240', :large => '600x600'}
    Spree::Image.attachment_definitions[:attachment][:path] = Spree::Config[:attachment_path]
    Spree::Image.attachment_definitions[:attachment][:default_url] = Spree::Config[:attachment_default_url]
    Spree::Image.attachment_definitions[:attachment][:default_style] = Spree::Config[:attachment_default_style]

    #used by admin products autocomplete
    def mini_url
      attachment.url(:mini, false)
    end

    def find_dimensions
      temporary = attachment.queued_for_write[:original]
      filename = temporary.path unless temporary.nil?
      filename = attachment.path if filename.blank?
      geometry = Paperclip::Geometry.from_file(filename)
      self.attachment_width  = geometry.width
      self.attachment_height = geometry.height
    end

    # if there are errors from the plugin, then add a more meaningful message
    def no_attachment_errors
      unless attachment.errors.empty?
        # uncomment this to get rid of the less-than-useful interrim messages
        # errors.clear
        errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
        false
      end
    end
  end
end

app/controllers/spree/orders_controller_decorator.rb
module Spree
  OrdersController.class_eval do

    include ProductCustomizations
    include AdHocUtils

    # the inbound variant is determined either from products[pid]=vid or variants[master_vid], depending on whether or not the product has_variants, or not
    #
    # Currently, we are assuming the inbound ad_hoc_option_values and customizations apply to the entire inbound product/variant 'group', as more surgery
    # needs to occur in the cart partial for this to be done 'right'
    #
    def populate
      @order = current_order(true)

      params[:products].each do |product_id,variant_id|
        quantity = params[:quantity].to_i if !params[:quantity].is_a?(Hash)
        quantity = params[:quantity][variant_id].to_i if params[:quantity].is_a?(Hash)
        @order.add_variant(Variant.find(variant_id), quantity, ad_hoc_option_value_ids, product_customizations) if quantity > 0
      end if params[:products]

      params[:variants].each do |variant_id, quantity|
        quantity = quantity.to_i
        @order.add_variant(Variant.find(variant_id), quantity, ad_hoc_option_value_ids, product_customizations) if quantity > 0
      end if params[:variants]

      fire_event('spree.cart.add')
      fire_event('spree.order.contents_changed')

      redirect_to cart_path
    end

  end
end

app/controllers/spree/products_controller.rb
module Spree
  class ProductsController < BaseController
    HTTP_REFERER_REGEXP = /^https?:\/\/[^\/]+\/t\/([a-z0-9\-\/]+)$/
    before_filter :load_product, :only => :show
    rescue_from ActiveRecord::RecordNotFound, :with => :render_404
    helper 'spree/taxons'

    respond_to :html

    def index
      
      @searcher = Config.searcher_class.new(params)
      @products = @searcher.retrieve_products
      
      respond_with(@products)
    end

    def show
      
      return unless @product

      @variants = Variant.active.includes([:option_values, :images]).where(:product_id => @product.id)
      @product_properties = ProductProperty.includes(:property).where(:product_id => @product.id)
      
      referer = request.env['HTTP_REFERER']

      if referer && referer.match(HTTP_REFERER_REGEXP)
        @taxon = Taxon.find_by_permalink($1)
      end

      respond_with(@product)
    end

    private
      def accurate_title
        @product ? @product.name : super
      end

      def load_product
        @product = Product.active.find_by_permalink!(params[:id])
      end
  end
end

app/views/spree/orders/_congrats.html.erb
	<div align="center" id="maindiv">

	<div id="wrap">
	
<div style="width:100%; background: url(/assets/lightbox_bg.jpg); border-radius: 10px 10px 10px 10px;">
 <div class="lightbox_title4">Congrats!</div>
 <div style="padding:20px; border-top:1px solid #fff">

<table width="100%" border="0" cellspacing="5" cellpadding="0">
  
    <tr>
      <td align="left" valign="middle" class="cart_line"><label></label>
	  Thanks for your purchase! You'll receive a receipt via email. <br />
	  There's one more thing that you can help us do, which is to get the word out!<br />
        <label></label>
        <br />
		
		<div style="width:auto; float:left; height:auto; margin-top:10px"><a href="#"><img src="/assets/facebook.jpg" alt="" width="28" height="29" border="0" /></a>
		&nbsp;&nbsp;
		
		<a href="#"><img src="/assets/twitter.jpg" alt="" width="36" height="27" border="0" /></a>
	  <a href="#"></a> <a href="#"></a></div>		</td>
    </tr>
    <tr>
    <td align="right" valign="middle" style="border-top: 1px solid #e9e9e9; padding-top:20px">&nbsp;</td>
    </tr>
</table>

	    </div>
</div>

		 
		  

			
		  </div> 
  
  
	
	
	
	
	
	
	</div>
	

	
	

app/views/spree/orders/_form.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @order } %>
<table id="cart-detail" data-hook width="100%" border="0" cellspacing="0" bordercolor="white">
 <thead>
    <tr data-hook="cart_items_headers">
      <th style="padding-left:20px;text-align:left;"><%= t(:item) %></th>
      <th style="padding-left:20px;text-align:left;"><%= t(:price) %></th>
      <th style="padding-left:20px;text-align:left;"><%= t(:qty) %></th>
      <th style="padding-left:20px;text-align:left;"><%= t(:total) %></th>
      <th style="padding-left:20px;text-align:left;">Remove</th>
    </tr>
  </thead>
  <tbody id="line_items" data-hook >
  	<div style="width:100%; background: url(/assets/lightbox_bg.jpg); border-radius: 10px 10px 10px 10px;margin-bottom: 15px;">
 <div class="lightbox_title">Your Cart</div>

    <%= order_form.fields_for :line_items do |item_form| %>
      <%= render :partial => 'line_item', :locals => { :variant => item_form.object.variant, :line_item => item_form.object, :item_form => item_form } %>
    <% end %>
    </div>
    </div>
  </tbody>
</table>

app/views/spree/orders/_line_item.html.erb
<tr class="<%= cycle('', 'alt') %> line-item">

  <td data-hook="cart_item_description" align="left" style="padding-left: 20px;width: 30%;">
    <h3><%= variant.product.name %></h3>
    <%= variant.options_text %>
    <% if @order.insufficient_stock_lines.include? line_item %>
      <span class="out-of-stock">
        <%= variant.in_stock? ? t(:insufficient_stock, :on_hand => variant.on_hand) : t(:out_of_stock) %><br />
      </span>
    <% end %>

  </td>
  <td data-hook="cart_item_price" align="left" style="color:#e57520;font-size: 15px;padding-left: 20px;width: 20%;">
    <%= number_to_currency line_item.price %>
  </td>
  <td data-hook="cart_item_quantity" align="left" style="	padding-left:20px;width: 10%;">
  	<style>
  		.aa{
  			width:29px;
  		
  		}
  	</style>
    <%= item_form.number_field :quantity, :min => 0, :class => "line_item_quantity aa", :size => 5 %>
  </td>
  <td data-hook="cart_item_total" align="left" style="color:#e57520;font-size: 15px;padding-left: 20px;width: 20%;">
    <%= number_to_currency(line_item.price * line_item.quantity) unless line_item.quantity.nil? %>
  </td>
  <td data-hook="cart_item_delete" align="left" style="float:left padding-left: 20px;width: 10%;">
    <%= link_to image_tag('icons/delete.png'), '#', :class => 'delete', :id => "delete_#{dom_id(line_item)}" %>
  </td>
</tr>

app/views/spree/orders/edit.html.erb
<% @body_id = 'cart' %>

<% if @order.line_items.empty? %>

  <div data-hook="empty_cart">
 	<center><h2>Your Cart is empty</h2></center>  
 
  </div>

<% else %>
  <div data-hook="outside_cart_form" style="margin:5px 25px 25px 25px;">
    <%= form_for @order, :url => update_cart_path, :html => {:id => 'update-cart'} do |order_form| %>
      <div data-hook="inside_cart_form"> 
<div style="overflow-y: scroll;height: 300px;">
        <div data-hook="cart_items" >
          <%= render :partial => 'form', :locals => { :order_form => order_form } %>
        </div><br/>
          <div class="links columns ten alpha" data-hook="cart_buttons" style="margin-left:83%;">
          <%= button_tag :class => "button", :id => 'update-button' do %>
            <%= t(:update) %>
          <% end %>
         
        </div><br/>
 <div id="subtotal" data-hook class="columns six omega">
         <table width="100%" cellspacing="0" cellpadding="10">
        <tr  class="cart_line2">
         		<th align="left" style=" background:url(/assets/bullet2.jpg) no-repeat 3px 9px;width:30%;padding:0 0 0 15px;">Sub total</th>
         		<th style="width:20%;">&nbsp;</th>
         		<th  style="width:10%;">&nbsp;</th>
         		<th align="left" style="padding-left:20px;width: 20%;"> <%= order_subtotal(@order) %></th>
         		<th  style="width:10%;">&nbsp;</th>	
         	</tr>
         </table>
        </div>
        </div>
        <div class="links columns ten alpha" data-hook="cart_buttons">
          <table border="0" align=left cellpadding="15" width="50%">
         <tr>
            	<td align="left">
         <a href='/checkout' style="background:url(/assets/checkout.jpg) no-repeat; border:0; border-width:0; cursor:pointer; width:121px; height:35px;padding: 7px 87px 36px 35px;" id = 'checkout-link' ></a>
              <a onclick=" parent.eval('tb_remove()')" style="background:url(/assets/continue_shopping.jpg) no-repeat; border:0; border-width:0; cursor:pointer; width:225px; height:35px;padding: 7px 220px 36px 35px;"></a>

         </table>
        </div>
      </div>
    <% end %>
  </div>

<% end %>

app/views/spree/orders/new.html.erb
<% @body_id = 'cart' %>



<%= form_for @order, :url =>'#', :method => :put do |order_form| %>
  <%= render :partial => 'form', :locals => { :order_form => order_form } %>
<% end %>

<p><%= link_to t(:continue_shopping), products_path %></p>

app/views/spree/orders/show.html.erb
<%= render 'spree/orders/congrats'%>