config/routes.rb
Spreedemo::Application.routes.draw do
  
  mount Spree::Core::Engine, :at => '/'
  
    root :to => 'products#index'

  resources :products

  match '/locale/set', :to => 'locale#set'

  resources :tax_categories

  resources :states, :only => :index

  match '/checkout/update/:state', :to => 'checkout#update', :as => :update_checkout
  match '/checkout/:state', :to => 'checkout#edit', :as => :checkout_state
  match '/checkout', :to => 'checkout#edit', :state => 'address', :as => :checkout

  resources :orders do
    post :populate, :on => :collection

    resources :line_items
    resources :creditcards
    resources :creditcard_payments

    resources :shipments do
      member do
        get :shipping_method
      end
    end

  end
  get '/cart', :to => 'orders#edit', :as => :cart
  put '/cart', :to => 'orders#update', :as => :update_cart
  put '/cart/empty', :to => 'orders#empty', :as => :empty_cart

  resources :shipments do
    member do
      get :shipping_method
      put :shipping_method
    end
  end

  match '/t/*id', :to => 'taxons#show', :as => :nested_taxons

  namespace :admin do
    resources :adjustments
    resources :zones
    resources :users do
      member do
        post :dismiss_banner
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories
    resources :configurations, :only => :index
    resources :products do
      resources :product_properties
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :option_types do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
          post :update_positions
        end
      end
      resources :taxons do
        member do
          get :select
          delete :remove
        end
        collection do
          post :available
          post :batch_select
          get  :selected
        end
      end
    end

    resources :option_types do
      collection do
        post :update_positions
      end
    end

    resources :properties do
      collection do
        get :filtered
      end
    end

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :inventory_settings
    resource :image_settings
    resources :google_analytics

    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
        get :history
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      member do
        get :get_children
      end

      resources :taxons
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :shipments
    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource  :tax_settings
    resources :calculators

    resources :trackers
    resources :payment_methods
    resources :mail_methods do
      member do
        post :testmail
      end
    end
  end

  match '/admin', :to => 'admin/orders#index', :as => :admin

  match '/content/cvv', :to => 'content#cvv'
  match '/content/*path', :to => 'content#show', :via => :get, :as => :content
  
  
  
  
  
  

end

app/models/spree/address.rb
module Spree
  class Address < ActiveRecord::Base
    belongs_to :country
    belongs_to :state

    has_many :shipments

    # validates :firstname, :lastname, :address1, :city, :zipcode, :country, :phone, :presence => true
    # validate :state_validate

    attr_accessible :firstname, :lastname, :address1, :address2,
                    :city, :zipcode, :country_id, :state_id,
                    :country, :state, :phone, :state_name,
                    :company, :alternative_phone,:full_name

    def full_name  
    [firstname, lastname].join(' ')  
  end  
  
  # Setter  
  def full_name=(name)  
    split = name.split(' ', 2)  
    self.firstname = split.first  
    self.lastname = split.last  
  end  

    # Disconnected since there's no code to display error messages yet OR matching client-side validation
    def phone_validate
      return if phone.blank?
      n_digits = phone.scan(/[0-9]/).size
      valid_chars = (phone =~ /^[-+()\/\s\d]+$/)
      errors.add :phone, :invalid unless (n_digits > 5 && valid_chars)
    end

    def self.default
      country = Spree::Country.find(Spree::Config[:default_country_id]) rescue Spree::Country.first
      new({:country => country}, :without_protection => true)
    end

    # Can modify an address if it's not been used in an order (but checkouts controller has finer control)
    # def editable?
    #   new_record? || (shipments.empty? && checkouts.empty?)
    # end

    def full_name
      "#{firstname} #{lastname}".strip
    end

    def state_text
      state.nil? ? state_name : (state.abbr.blank? ? state.name : state.abbr)
    end

    def zone
      (state && state.zone) || (country && country.zone)
    end

    def zones
      Zone.match(self)
    end

    def same_as?(other)
      return false if other.nil?
      attributes.except('id', 'updated_at', 'created_at') == other.attributes.except('id', 'updated_at', 'created_at')
    end

    alias same_as same_as?

    def to_s
      "#{full_name}: #{address1}"
    end

    def clone
      self.class.new(self.attributes.except('id', 'updated_at', 'created_at'))
    end

    def ==(other_address)
      self_attrs = self.attributes
      other_attrs = other_address.respond_to?(:attributes) ? other_address.attributes : {}

      [self_attrs, other_attrs].each { |attrs| attrs.except!('id', 'created_at', 'updated_at', 'order_id') }

      self_attrs == other_attrs
    end

    def empty?
      attributes.except('id', 'created_at', 'updated_at', 'order_id', 'country_id').all? { |_, v| v.nil? }
    end

    # Generates an ActiveMerchant compatible address hash
    def active_merchant_hash
      {
        :name => full_name,
        :address1 => address1,
        :address2 => address2,
        :city => city,
        :state => state_text,
        :zip => zipcode,
        :country => country.try(:iso),
        :phone => phone
      }
    end

    private

      def state_validate
        # Skip state validation without country (also required)
        # or when disabled by preference
        return if country.blank? || !Spree::Config[:address_requires_state]

        # ensure associated state belongs to country
        if state.present?
          if state.country == country
            self.state_name = nil #not required as we have a valid state and country combo
          else
            if state_name.present?
              self.state = nil
            else
              errors.add(:state, :invalid)
            end
          end
        end

        # ensure state_name belongs to country without states, or that it matches a predefined state name/abbr
        if state_name.present?
          if country.states.present?
            states = country.states.find_all_by_name_or_abbr(state_name)

            if states.size == 1
              self.state = states.first
              self.state_name = nil
            else
              errors.add(:state, :invalid)
            end
          end
        end

        # ensure at least one state field is populated
        errors.add :state, :blank if state.blank? && state_name.blank?
      end

  end
end

app/models/spree/current_order_decorator.rb
Spree::Core::CurrentOrder.module_eval do
  # Associate the new order with the currently authenticated user before saving
  def before_save_new_order
    @current_order.user ||= current_user
  end

  def after_save_new_order
    # make sure the user has permission to access the order (if they are a guest)
    return if current_user
    session[:access_token] = @current_order.token
  end
end

app/models/spree/image.rb
module Spree
  class Image < Asset
    validates_attachment_presence :attachment
    validate :no_attachment_errors

    attr_accessible :alt, :attachment, :position, :viewable_type, :viewable_id

    has_attached_file :attachment,
                      :styles => { :mini => '48x48>', :small => '100x100>', :product => '240x240>', :large => '600x600>' },
                      :default_style => :product,
                      :url => '/spree/products/:id/:style/:basename.:extension',
                      :path => ':rails_root/public/spree/products/:id/:style/:basename.:extension'
    # save the w,h of the original image (from which others can be calculated)
    # we need to look at the write-queue for images which have not been saved yet
    after_post_process :find_dimensions

    # Load user defined paperclip settings
    if Spree::Config[:use_s3]
      s3_creds = { :access_key_id => Spree::Config[:s3_access_key], :secret_access_key => Spree::Config[:s3_secret], :bucket => Spree::Config[:s3_bucket] }
      Spree::Image.attachment_definitions[:attachment][:storage] = :s3
      Spree::Image.attachment_definitions[:attachment][:s3_credentials] = s3_creds
      Spree::Image.attachment_definitions[:attachment][:s3_headers] = ActiveSupport::JSON.decode(Spree::Config[:s3_headers])
      Spree::Image.attachment_definitions[:attachment][:bucket] = Spree::Config[:s3_bucket]
    end

    Spree::Image.attachment_definitions[:attachment][:styles] = { :mini => '48x48', :small => '100x100', :product => '240x240', :large => '600x600'}
    Spree::Image.attachment_definitions[:attachment][:path] = Spree::Config[:attachment_path]
    Spree::Image.attachment_definitions[:attachment][:default_url] = Spree::Config[:attachment_default_url]
    Spree::Image.attachment_definitions[:attachment][:default_style] = Spree::Config[:attachment_default_style]

    #used by admin products autocomplete
    def mini_url
      attachment.url(:mini, false)
    end

    def find_dimensions
      temporary = attachment.queued_for_write[:original]
      filename = temporary.path unless temporary.nil?
      filename = attachment.path if filename.blank?
      geometry = Paperclip::Geometry.from_file(filename)
      self.attachment_width  = geometry.width
      self.attachment_height = geometry.height
    end

    # if there are errors from the plugin, then add a more meaningful message
    def no_attachment_errors
      unless attachment.errors.empty?
        # uncomment this to get rid of the less-than-useful interrim messages
        # errors.clear
        errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
        false
      end
    end
  end
end

app/controllers/spree/orders_controller_decorator.rb
module Spree
  OrdersController.class_eval do

    include ProductCustomizations
    include AdHocUtils

    # the inbound variant is determined either from products[pid]=vid or variants[master_vid], depending on whether or not the product has_variants, or not
    #
    # Currently, we are assuming the inbound ad_hoc_option_values and customizations apply to the entire inbound product/variant 'group', as more surgery
    # needs to occur in the cart partial for this to be done 'right'
    #
    def populate
      @order = current_order(true)

      params[:products].each do |product_id,variant_id|
        quantity = params[:quantity].to_i if !params[:quantity].is_a?(Hash)
        quantity = params[:quantity][variant_id].to_i if params[:quantity].is_a?(Hash)
        @order.add_variant(Variant.find(variant_id), quantity, ad_hoc_option_value_ids, product_customizations) if quantity > 0
      end if params[:products]

      params[:variants].each do |variant_id, quantity|
        quantity = quantity.to_i
        @order.add_variant(Variant.find(variant_id), quantity, ad_hoc_option_value_ids, product_customizations) if quantity > 0
      end if params[:variants]

      fire_event('spree.cart.add')
      fire_event('spree.order.contents_changed')

      redirect_to cart_path
    end

  end
end

app/controllers/spree/products_controller.rb
module Spree
  class ProductsController < BaseController
    HTTP_REFERER_REGEXP = /^https?:\/\/[^\/]+\/t\/([a-z0-9\-\/]+)$/
    before_filter :load_product, :only => :show
    rescue_from ActiveRecord::RecordNotFound, :with => :render_404
    helper 'spree/taxons'

    respond_to :html

    def index
      
      @searcher = Config.searcher_class.new(params)
      @products = @searcher.retrieve_products
      
      respond_with(@products)
    end

    def show
      
      return unless @product

      @variants = Variant.active.includes([:option_values, :images]).where(:product_id => @product.id)
      @product_properties = ProductProperty.includes(:property).where(:product_id => @product.id)
      
      referer = request.env['HTTP_REFERER']

      if referer && referer.match(HTTP_REFERER_REGEXP)
        @taxon = Taxon.find_by_permalink($1)
      end

      respond_with(@product)
    end

    private
      def accurate_title
        @product ? @product.name : super
      end

      def load_product
        @product = Product.active.find_by_permalink!(params[:id])
      end
  end
end

app/views/spree/checkout/_address.html.erb
 	<div style="width:90%; background: url(/assets/lightbox_bg.jpg); border-radius: 10px 10px 10px 10px;margin-left:30px;margin-bottom: 15px;">

 <div class="lightbox_title2">Shipping and Billing Address</div>
<div class="columns omega six" data-hook="shipping_fieldset_wrapper">
<fieldset id="shipping" data-hook style="border: 0;">
<div style="width:100%; background: url(/assets/lightbox_bg.jpg); border-radius: 10px 10px 10px 10px;">

<div class="columns omega six" data-hook="shipping_fieldset_wrapper">

  <%= form.fields_for :ship_address do |ship_form| %>
<table><tr><th>Shipping :</th>
    <p class="field checkbox" data-hook="use_billing" >
      <%= check_box_tag 'order[use_billing]', '1', (!(@order.bill_address.empty? && @order.ship_address.empty?) && @order.bill_address.same_as?(@order.ship_address)) %> 
      <%= label_tag :order_use_billing, t(:use_billing_address), :id => 'use_billing' %>
    </p>
    <div class="inner" data-hook="shipping_inner">
    
      <p class="field" id="sfirstname">
       
        <%= ship_form.hidden_field :firstname , :value => Spree::User.find_by_id(1).fname  %>
      </p>
      <p class="field" id="slastname">
  
        <%= ship_form.hidden_field :lastname , :value => Spree::User.find_by_id(1).lname %>
      </p>
     
      <p class="field" id="saddress1">
      <td>
       <%= ship_form.hidden_field :address1, :value => Spree::User.find_by_id(1).address %>This order will be bulk shipped to <%= Spree::User.find_by_id(1).address %> , <%= Spree::User.find_by_id(1).city %></td> 
      </p>
  
      <p class="field" id="scity">

        <%= ship_form.hidden_field :city, :value => Spree::User.find_by_id(1).city  %>
      </p>

      <p class="field" id="scountry">
		 <%= ship_form.hidden_field :country_id, :value => Spree::User.find_by_id(1).country_id %>
      </p>

      
        <p class="field" id="sstate">
	 	 <%= ship_form.hidden_field :state_id, :value =>Spree::User.find_by_id(1).state_id  %>
        </p>


      <p class="field" id="szipcode">

        <%= ship_form.hidden_field :zipcode, :value => Spree::User.find_by_id(1).zip %>
      </p>
      <p class="field" id="sphone">

        <%= ship_form.hidden_field :phone, :value => Spree::User.find_by_id(1).phone  %>
      </p>
      <% if Spree::Config[:alternative_shipping_phone] %>
        <p class="field" id="saltphone">
          <%= ship_form.label :alternative_phone, t(:alternative_phone) %><br />
          <%= ship_form.text_field :alternative_phone %>
        </p>
      <% end %>
    </div>
    </tr></table>
  <% end %>
</fieldset>
</div>

<div class="columns alpha six" data-hook="billing_fieldset_wrapper">
<fieldset id="billing" data-hook style="border: 0;">
  <%= form.fields_for :bill_address do |bill_form| %>
  <table> <tr><th rowspan="3" valign="top">Billing : </th>
    <div class="inner" data-hook="billing_inner" >
    <td>	<tr><td>
      <span class="field" id="bfirstname">
   	       <%= bill_form.text_field :full_name,:placeholder => "Full name",:class => "required"  %>
      </span>
    
       </td></tr><tr><td>
          <span class="field" id="saddress1">
      
       <%= bill_form.text_field :address1, :placeholder => "Address" ,:class => "required" %> 
      </span>
  
      <span class="field" id="bcity">
		  <%= bill_form.text_field :city, :placeholder => "City"  ,:class => "required" %>
      </span>
<div style="display: none">
    <p class="field" id="bcountry">
        <%= bill_form.label :country_id, t(:country) %><span class="req">*</span><br />
        <span id="bcountry">
          <%= bill_form.collection_select :country_id, available_countries, :id, :name, {}, {:class => 'required'} %>
        </span>
      </p>
      </div>
         <% if Spree::Config[:address_requires_state] %>
     <table cellspacing="0" cellpadding="2" style="margin-left: -3px;"><tr><td>   <p class="field" id="bstate">
          <% have_states = !@order.bill_address.country.states.empty? %>
          
          <%= bill_form.label :state, t(" ") %>
       
          <% state_elements = [
             bill_form.collection_select(:state_id, @order.bill_address.country.states,
                                :id, :name,{:include_blank => "Please select"},
                                
                                
                                {:class => have_states ? 'required' : 'hidden',
                                :disabled => !have_states}) 
             
             ].join.gsub('"', "'").gsub("\n", "")
          %>
          <%= javascript_tag do -%>
            document.write("<%== state_elements  %>");
          <% end -%>
      </p> </td> 
      <% end %>

<td>
      <span class="field" id="bzipcode">
		
        <%= bill_form.text_field :zipcode, :placeholder => "Zip Code" ,:class => "required"  %>
      </span></td></tr></table>
      <span class="field" id="bphone">
	       <%= bill_form.hidden_field :phone, :placeholder => "Phone" , :value => Spree::User.find_by_id(1).phone %>
      </span>
      <% if Spree::Config[:alternative_shipping_phone] %>
        <p class="field" id="saltphone">
          <%= bill_form.label :alternative_phone, t(:alternative_phone) %><br />
          <%= bill_form.text_field :alternative_phone %>
        </p>
      <% end %>
    </div>
  <% end %>
</fieldset>
</div>

<br/><br/><br/>
<div class="form-buttons" data-hook="buttons">
	
 <input type="submit" name="Submit" value="" style="background:url(/assets/continue.jpg) repeat-x; border:0; border-width:0; cursor:pointer; width:121px; height:35px;" />



</div>

</div>

app/views/spree/checkout/_confirm.html.erb
<fieldset id="order_details" data-hook>
  <div class="clear"></div>
  <legend><%= t(@order.state, :scope => :order_state).titleize %></legend>
  <%= render :partial => 'spree/shared/order_details', :locals => { :order => @order } %>
</fieldset>

<br />

<div class="form-buttons" data-hook="buttons">
<input type="submit" name="Submit" value="" style="background:url(/assets/place.jpg) repeat-x; border:0; border-width:0; cursor:pointer; width:121px; height:35px;" />

</div>

app/views/spree/checkout/_delivery.html.erb
<div style="width:100%; background: url(assets/lightbox_bg.jpg); border-radius: 10px 10px 10px 10px;">
<div class="lightbox_title2">Shipping Method </div>
<div style="padding:20px; border-top:1px solid #fff">


 	<table width="100%" border="0" cellspacing="5" cellpadding="0">
        <% @order.rate_hash.each do |shipping_method| %>

  <tr>
    <td align="left" valign="middle" class="cart_line"><label>
            <%= radio_button(:order, :shipping_method_id, shipping_method[:id]) %>    
            <% if Spree::Config[:shipment_inc_vat] %>
              <%= shipping_method[:name] %> <%= format_price (1 + Spree::TaxRate.default) * shipping_method[:cost] %>
            <% else %>
            <%= shipping_method[:name] %> <%= number_to_currency shipping_method[:cost] %>
            <% end %>
          </label> </td>
        <% end %>
     
   
    <% if Spree::Config[:shipping_instructions] && @order.rate_hash.present? %>
      <p id="minstrs" data-hook>
        <%= form.label :special_instructions, t(:shipping_instructions) %><br />
        <%= form.text_area :special_instructions, :cols => 40, :rows => 7 %>
      </p>
    <% end %>


 <tr>
    <td colspan="3" align="left" valign="middle" class="cart_line">

      <input type="submit" name="Submit" value="" style="background:url(../assets/continue.jpg) repeat-x; border:0; border-width:0; cursor:pointer; width:121px; height:35px;" />
  	</td>
    </tr>
</table>

  </div>  </div>

app/views/spree/checkout/_payment.html.erb
<fieldset id="payment" data-hook style="border: 0px;">

	<div style="width:100%; background: url(/assets/lightbox_bg.jpg); border-radius: 10px 10px 10px 10px;margin-bottom: 15px;">
  <div class="lightbox_title3">Payment Info</div>
  <div data-hook="checkout_payment_step" >
    <% @order.available_payment_methods.each do |method| %>
      	<span style="display:none;">
        <%= radio_button_tag "order[payments_attributes][][payment_method_id]", method.id, method == @order.payment_method %>
        <%= t(method.name, :scope => :payment_methods, :default => method.name) %>
      </span>

    <% end %>

    <ul id="payment-methods" data-hook type='none'>
      <% @order.available_payment_methods.each do |method| %>
        <li id="payment_method_<%= method.id %>" class="<%= 'last' if method == @order.available_payment_methods.last %>" data-hook >
          <fieldset style="border:0;">
            <%= render :partial => "spree/checkout/payment/#{method.method_type}", :locals => { :payment_method => method } %>
          </fieldset>
        </li>
      <% end %>
    </ul>
   
    <div data-hook="coupon_code_field" data-hook></div>
  </div>
</fieldset>
	
<div class="form-buttons" data-hook="buttons">
      <input type="submit" name="Submit" value="" style="background:url(/assets/purchase_bg.jpg) repeat-x; border:0; border-width:0; cursor:pointer; width:121px; height:35px;margin-left:50px; " />
  <script>disableSaveOnClick();</script>
</div>
</div>

app/views/spree/checkout/edit.html.erb
<% content_for :head do %>
  <%= javascript_include_tag states_url %>
<% end %>



<div id="checkout" data-hook>  
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @order } %>
  
  <div class="row" data-hook="checkout_header">
    <h1 class="columns three alpha" data-hook="checkout_title"><%= t(:checkout) %></h1>
    <div class="columns thirteen omega" data-hook="checkout_progress"><%= checkout_progress %></div>
  </div>
  
  <div class="row" data-hook="checkout_content">
    <div class="columns <%= if @order.state != 'confirm' then 'alpha twelve' else 'alpha omega sixteen' end %>" data-hook="checkout_form_wrapper">
      
      <%= form_for @order, :url => update_checkout_path(@order.state), :html => { :id => "checkout_form_#{@order.state}" } do |form| %>
        <%= render @order.state, :form => form %>
        <%= submit_tag nil, :id => 'post-final', :style => 'display:none;' %>
      <% end %>
    </div>    
    <% if @order.state != 'confirm' %>
      <div id="checkout-summary" data-hook="checkout_summary_box" class="columns omega four">
        <%= render :partial => 'summary', :locals => { :order => @order } %>
      </div>
    <% end %>
  </div>

</div>

app/views/spree/checkout/registration.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @user } %>

<div id="registration" data-hook>
  <div id="account" class="columns alpha eight">
    <!-- TODO: add partial with registration form -->
  </div>
  <% if Spree::Config[:allow_guest_checkout] %>
  <center style="margin-left: 30px;">
  <div style="width:100%; background: url(/assets/lightbox_bg.jpg); border-radius: 10px 10px 10px 10px;margin-bottom: 15px;">
   <div class="lightbox_title1">Checkout as a Guest </div>
      <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @order } %>

      <%= form_for @order, :url => update_checkout_registration_path, :method => :put, :html => { :id => 'checkout_form_registration' } do |f| %>
   <table width="80%" border="0" cellspacing="0" cellpadding="5" style="float:left;padding-left: 10px;">
  <tr>
    <td align="left" valign="middle" ><span>Email</span><br/>
     <label>
     	  <%= f.email_field :email, :class => 'list5'   %></td>
  		<td>We will send your purchase receipt to this email. <a href="http://causera.org/privacy-policy" target="_new">View our privacy policy</a> 
    </label></td>
  </tr>

            <tr>
  
    <td align="left" valign="top" colspan="3"><label>
      <input type="submit" name="Submit" value="" style="background:url(../assets/continue.jpg) repeat-x; border:0; border-width:0; cursor:pointer; width:121px; height:35px;" />
&nbsp;    </label></td>
    </tr>
  
</table>

      <% end %>
   
   
  <% end %>
</div>
</div>