config/routes.rb
Spreedemo::Application.routes.draw do
  
  mount Spree::Core::Engine, :at => '/'
  
    root :to => 'products#index'

  resources :products

  match '/locale/set', :to => 'locale#set'

  resources :tax_categories

  resources :states, :only => :index

  match '/checkout/update/:state', :to => 'checkout#update', :as => :update_checkout
  match '/checkout/:state', :to => 'checkout#edit', :as => :checkout_state
  match '/checkout', :to => 'checkout#edit', :state => 'address', :as => :checkout

  resources :orders do
    post :populate, :on => :collection

    resources :line_items
    resources :creditcards
    resources :creditcard_payments

    resources :shipments do
      member do
        get :shipping_method
      end
    end

  end
  get '/cart', :to => 'orders#edit', :as => :cart
  put '/cart', :to => 'orders#update', :as => :update_cart
  put '/cart/empty', :to => 'orders#empty', :as => :empty_cart

  resources :shipments do
    member do
      get :shipping_method
      put :shipping_method
    end
  end

  match '/t/*id', :to => 'taxons#show', :as => :nested_taxons

  namespace :admin do
    resources :adjustments
    resources :zones
    resources :users do
      member do
        post :dismiss_banner
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories
    resources :configurations, :only => :index
    resources :products do
      resources :product_properties
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :option_types do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
          post :update_positions
        end
      end
      resources :taxons do
        member do
          get :select
          delete :remove
        end
        collection do
          post :available
          post :batch_select
          get  :selected
        end
      end
    end

    resources :option_types do
      collection do
        post :update_positions
      end
    end

    resources :properties do
      collection do
        get :filtered
      end
    end

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :inventory_settings
    resource :image_settings
    resources :google_analytics

    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
        get :history
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      member do
        get :get_children
      end

      resources :taxons
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :shipments
    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource  :tax_settings
    resources :calculators

    resources :trackers
    resources :payment_methods
    resources :mail_methods do
      member do
        post :testmail
      end
    end
  end

  match '/admin', :to => 'admin/orders#index', :as => :admin

  match '/content/cvv', :to => 'content#cvv'
  match '/content/*path', :to => 'content#show', :via => :get, :as => :content
  
  
  
  
  
  

end

app/models/spree/address.rb
module Spree
  class Address < ActiveRecord::Base
    belongs_to :country
    belongs_to :state

    has_many :shipments

    # validates :firstname, :lastname, :address1, :city, :zipcode, :country, :phone, :presence => true
    # validate :state_validate

    attr_accessible :firstname, :lastname, :address1, :address2,
                    :city, :zipcode, :country_id, :state_id,
                    :country, :state, :phone, :state_name,
                    :company, :alternative_phone,:full_name

    def full_name  
    [firstname, lastname].join(' ')  
  end  
  
  # Setter  
  def full_name=(name)  
    split = name.split(' ', 2)  
    self.firstname = split.first  
    self.lastname = split.last  
  end  

    # Disconnected since there's no code to display error messages yet OR matching client-side validation
    def phone_validate
      return if phone.blank?
      n_digits = phone.scan(/[0-9]/).size
      valid_chars = (phone =~ /^[-+()\/\s\d]+$/)
      errors.add :phone, :invalid unless (n_digits > 5 && valid_chars)
    end

    def self.default
      country = Spree::Country.find(Spree::Config[:default_country_id]) rescue Spree::Country.first
      new({:country => country}, :without_protection => true)
    end

    # Can modify an address if it's not been used in an order (but checkouts controller has finer control)
    # def editable?
    #   new_record? || (shipments.empty? && checkouts.empty?)
    # end

    def full_name
      "#{firstname} #{lastname}".strip
    end

    def state_text
      state.nil? ? state_name : (state.abbr.blank? ? state.name : state.abbr)
    end

    def zone
      (state && state.zone) || (country && country.zone)
    end

    def zones
      Zone.match(self)
    end

    def same_as?(other)
      return false if other.nil?
      attributes.except('id', 'updated_at', 'created_at') == other.attributes.except('id', 'updated_at', 'created_at')
    end

    alias same_as same_as?

    def to_s
      "#{full_name}: #{address1}"
    end

    def clone
      self.class.new(self.attributes.except('id', 'updated_at', 'created_at'))
    end

    def ==(other_address)
      self_attrs = self.attributes
      other_attrs = other_address.respond_to?(:attributes) ? other_address.attributes : {}

      [self_attrs, other_attrs].each { |attrs| attrs.except!('id', 'created_at', 'updated_at', 'order_id') }

      self_attrs == other_attrs
    end

    def empty?
      attributes.except('id', 'created_at', 'updated_at', 'order_id', 'country_id').all? { |_, v| v.nil? }
    end

    # Generates an ActiveMerchant compatible address hash
    def active_merchant_hash
      {
        :name => full_name,
        :address1 => address1,
        :address2 => address2,
        :city => city,
        :state => state_text,
        :zip => zipcode,
        :country => country.try(:iso),
        :phone => phone
      }
    end

    private

      def state_validate
        # Skip state validation without country (also required)
        # or when disabled by preference
        return if country.blank? || !Spree::Config[:address_requires_state]

        # ensure associated state belongs to country
        if state.present?
          if state.country == country
            self.state_name = nil #not required as we have a valid state and country combo
          else
            if state_name.present?
              self.state = nil
            else
              errors.add(:state, :invalid)
            end
          end
        end

        # ensure state_name belongs to country without states, or that it matches a predefined state name/abbr
        if state_name.present?
          if country.states.present?
            states = country.states.find_all_by_name_or_abbr(state_name)

            if states.size == 1
              self.state = states.first
              self.state_name = nil
            else
              errors.add(:state, :invalid)
            end
          end
        end

        # ensure at least one state field is populated
        errors.add :state, :blank if state.blank? && state_name.blank?
      end

  end
end

app/models/spree/current_order_decorator.rb
Spree::Core::CurrentOrder.module_eval do
  # Associate the new order with the currently authenticated user before saving
  def before_save_new_order
    @current_order.user ||= current_user
  end

  def after_save_new_order
    # make sure the user has permission to access the order (if they are a guest)
    return if current_user
    session[:access_token] = @current_order.token
  end
end

app/models/spree/image.rb
module Spree
  class Image < Asset
    validates_attachment_presence :attachment
    validate :no_attachment_errors

    attr_accessible :alt, :attachment, :position, :viewable_type, :viewable_id

    has_attached_file :attachment,
                      :styles => { :mini => '48x48>', :small => '100x100>', :product => '240x240>', :large => '600x600>' },
                      :default_style => :product,
                      :url => '/spree/products/:id/:style/:basename.:extension',
                      :path => ':rails_root/public/spree/products/:id/:style/:basename.:extension'
    # save the w,h of the original image (from which others can be calculated)
    # we need to look at the write-queue for images which have not been saved yet
    after_post_process :find_dimensions

    # Load user defined paperclip settings
    if Spree::Config[:use_s3]
      s3_creds = { :access_key_id => Spree::Config[:s3_access_key], :secret_access_key => Spree::Config[:s3_secret], :bucket => Spree::Config[:s3_bucket] }
      Spree::Image.attachment_definitions[:attachment][:storage] = :s3
      Spree::Image.attachment_definitions[:attachment][:s3_credentials] = s3_creds
      Spree::Image.attachment_definitions[:attachment][:s3_headers] = ActiveSupport::JSON.decode(Spree::Config[:s3_headers])
      Spree::Image.attachment_definitions[:attachment][:bucket] = Spree::Config[:s3_bucket]
    end

    Spree::Image.attachment_definitions[:attachment][:styles] = { :mini => '48x48', :small => '100x100', :product => '240x240', :large => '600x600'}
    Spree::Image.attachment_definitions[:attachment][:path] = Spree::Config[:attachment_path]
    Spree::Image.attachment_definitions[:attachment][:default_url] = Spree::Config[:attachment_default_url]
    Spree::Image.attachment_definitions[:attachment][:default_style] = Spree::Config[:attachment_default_style]

    #used by admin products autocomplete
    def mini_url
      attachment.url(:mini, false)
    end

    def find_dimensions
      temporary = attachment.queued_for_write[:original]
      filename = temporary.path unless temporary.nil?
      filename = attachment.path if filename.blank?
      geometry = Paperclip::Geometry.from_file(filename)
      self.attachment_width  = geometry.width
      self.attachment_height = geometry.height
    end

    # if there are errors from the plugin, then add a more meaningful message
    def no_attachment_errors
      unless attachment.errors.empty?
        # uncomment this to get rid of the less-than-useful interrim messages
        # errors.clear
        errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
        false
      end
    end
  end
end

app/controllers/spree/orders_controller_decorator.rb
module Spree
  OrdersController.class_eval do

    include ProductCustomizations
    include AdHocUtils

    # the inbound variant is determined either from products[pid]=vid or variants[master_vid], depending on whether or not the product has_variants, or not
    #
    # Currently, we are assuming the inbound ad_hoc_option_values and customizations apply to the entire inbound product/variant 'group', as more surgery
    # needs to occur in the cart partial for this to be done 'right'
    #
    def populate
      @order = current_order(true)

      params[:products].each do |product_id,variant_id|
        quantity = params[:quantity].to_i if !params[:quantity].is_a?(Hash)
        quantity = params[:quantity][variant_id].to_i if params[:quantity].is_a?(Hash)
        @order.add_variant(Variant.find(variant_id), quantity, ad_hoc_option_value_ids, product_customizations) if quantity > 0
      end if params[:products]

      params[:variants].each do |variant_id, quantity|
        quantity = quantity.to_i
        @order.add_variant(Variant.find(variant_id), quantity, ad_hoc_option_value_ids, product_customizations) if quantity > 0
      end if params[:variants]

      fire_event('spree.cart.add')
      fire_event('spree.order.contents_changed')

      redirect_to cart_path
    end

  end
end

app/controllers/spree/products_controller.rb
module Spree
  class ProductsController < BaseController
    HTTP_REFERER_REGEXP = /^https?:\/\/[^\/]+\/t\/([a-z0-9\-\/]+)$/
    before_filter :load_product, :only => :show
    rescue_from ActiveRecord::RecordNotFound, :with => :render_404
    helper 'spree/taxons'

    respond_to :html

    def index
      
      @searcher = Config.searcher_class.new(params)
      @products = @searcher.retrieve_products
      
      respond_with(@products)
    end

    def show
      
      return unless @product

      @variants = Variant.active.includes([:option_values, :images]).where(:product_id => @product.id)
      @product_properties = ProductProperty.includes(:property).where(:product_id => @product.id)
      
      referer = request.env['HTTP_REFERER']

      if referer && referer.match(HTTP_REFERER_REGEXP)
        @taxon = Taxon.find_by_permalink($1)
      end

      respond_with(@product)
    end

    private
      def accurate_title
        @product ? @product.name : super
      end

      def load_product
        @product = Product.active.find_by_permalink!(params[:id])
      end
  end
end

app/views/spree/shared/_cart_form.html.erb
ABC

app/views/spree/shared/_head.html.erb
<meta charset="utf-8">

<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame -->
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<title><%= title %></title>

<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1" name="viewport">

<%== meta_data_tags %>

<%= favicon_link_tag image_path('favicon.ico') %>

<%= stylesheet_link_tag 'style','store/spree-flexi-variants' %>

<%= csrf_meta_tags %>
<%= javascript_include_tag 'store/all' %>

<!--[if lt IE 9]>
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<%= yield :head %>

app/views/spree/shared/_products.html.erb
<%= stylesheet_link_tag 'style', 'fotorama','lightbox' %>

  
<%= javascript_include_tag "fotorama.js",'lightbox1' %>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>



<head> 

    <script src="http://malsup.github.com/jquery.form.js"></script> 

    
</head> 
 
		<body >
  <div align="center" id="maindiv">
	

	
	<div id="header1">
	  <div id="header_wrap">
	  <div id="logo"><a href="#"><img src="/assets/logo.jpg" alt="" border="0" /></a></div>
	  
	  <div id="slogan">Annual Alumni Campaign</div>
	  
	  <div id="sn">
	  
	  <div id="share">Help us! Share this with friends</div>
	  <a href="#"><img src="/assets/facebook.jpg" alt="Facebook" title="Facebook" border="0" /></a> <a href="#"><img src="/assets/twitter.jpg" alt="Twitter" title="Twitter" border="0" style="margin-left:10px"/></a></div>
	  
	  </div>
	</div>
	
	
	<div id="wrap">
	
	<div id="alert">
	<div id="alert_image"><img src="/assets/alert.png" alt="" /></div>
	<div>Only <span class="orange">4 days</span> left to place your order!<br />
    <span class="smalltext">All orders must be placed by on 9/17/2012</span></div>
	</div>
	
	
	<div id="box_wrap">
    <div id="box1" style=" background-image:url(/assets/tick.jpg); background-repeat:no-repeat; background-position:2px 2px;">Our goal is <span class="orange">$150,000
	</span>
      <div id="progress"></div><label id="amount">100%</label>
	</div>
	
	
	<div id="box2"><div style="padding:3px 0 3px 30px; background:url(/assets/user.jpg) no-repeat" >Our supporters...</div>
	<div id="white_box"><div class="white_smallbox"><strong>George and Julie</strong> <br />
	  <span class="smalltext">22 minutes ago</span></div>
	<div class="white_smallbox"><strong>George and Julie</strong> <br />
	  <span class="smalltext">22 minutes ago</span></div>
	<div class="white_smallbox"><strong>George and Julie</strong> <br />
	  <span class="smalltext">22 minutes ago</span></div>
	<div class="white_smallbox"><strong>George and Julie</strong> <br />
	  <span class="smalltext">22 minutes ago</span></div>
	<div class="white_smallbox_last"><strong>George and Julie</strong> <br />
	  <span class="smalltext">22 minutes ago</span></div>
	</div>
	</div>
	
	
  </div>
  
  
  
	
	<div id="leftside">
	  <div class="leftbox1" style="background-image:url(/assets/fundraiser.jpg); background-repeat:no-repeat; background-position:2px 10px">
	   <div class="heading">About this Fundraiser</div>
	    <div class="whitebg"><strong>In order to fund the new gym, we've set an ambitious goal of $150,000 this year. Thank you for your support!</strong>
	    <p>Annual Alumni Campaign - lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris commodo lacinia quam vel cursus. Vivamus vulputate, elit eget fringilla bibendum, quam turpis placerat eros, ac porttitor nibh lacus at dolor. Morbi sagittis urna sed mi vehicula porta. </p>
	    <p>Vestibulum nec quam urna, non suscipit nulla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus facilisis eleifend faucibus. Cum sociis natoque penatibus et magnis dis. </p>
	    <p>Vivamus viverra turpis sit amet metus consequat gravida sed eget enim. Curabitur aliquet consectetur magna nec vehicula. Fusce gravida arcu eu nunc pharetra lacinia. </p>
	    </div>
	  </div>
	  
	  
	  
	  
	  
	  <div class="leftbox1" style="background-image:url(/assets/setting.jpg); background-repeat:no-repeat; background-position:2px 10px">
	   <div class="heading">About this Fundraiser</div>
      <a href="#"><img src="/assets/video.jpg" alt="" width="242" height="112" border="0" /></a></div>
	  
	  
	  
	</div>
	
	

	<div id="rightside">
		<%
  paginated_products = @searcher.retrieve_products if params.key?(:keywords)
  paginated_products ||= products
%>

<% if products.empty? %>
<% @variants = Spree::Variant.active.includes([:option_values,:images]).where(:product_id => product.id) %> 

  <%= t(:no_products_found) %>
<% elsif params.key?(:keywords) %>
  <h6 class="search-results-title"><%= t(:search_results, :keywords => h(params[:keywords])) %></h6>
<% end %>

<% if products.any? %>

  <% reset_cycle('default') %>
  <% products.each do |product| %>

   <script> 
        // wait for the DOM to be loaded 
        jQuery(document).ready(function() { 
        jQuery("#myForm<%= product.id %>").validate({ 
              errorElement:'div',
              rules: {
                      "ad_hoc_option_values[1]":{ required: true },

                      "ad_hoc_option_values[2]":{ required:true }
                      },
              messages: {
                      
                      }
              });
      });
      
        $(document).ready(function() { 
            // bind 'myForm' and provide a simple callback function 
            $('#myForm<%= product.id %>').ajaxForm(function() { 
				javascript: tb_show('', '<%= cart_path %>?KeepThis=true&TB_iframe=true&height=380&width=950&modal=false', tb_pathToImage);
            }); 
        }); 
    </script> 
	
	 <div class="product_box">
	 	<div id="cart-forms" data-hook="cart_form">
	 	<%= form_for :order, :url => populate_orders_url ,:html => { :id => "myForm#{product.id}"} do |f| %>
	 	
	  <table width="100%" border="0" cellspacing="0" cellpadding="">
  <tr>
    <td width="40%" align="left" valign="top">
	
	<div id="container">

          	 
          	<% if Spree::Config[:show_zero_stock_products] || product.has_stock? %>
 <% if product.images.size > 1 %>
  <div class="fotorama">
       	<% product.images.each do |i| %>
        	    
              <%= link_to image_tag(i.attachment.url(:mini)), i.attachment.url(:product) %>
              
   			 <% end %>
 <% else %>
   <%= product_image(product, :itemprop => "image") %>
		<% end %>
  
     	<% end %> 
  </div>
	  </div>
	</td>
          <td align="left" valign="top">

	<div class="discription">
	   <span class="heading2"><%= truncate(product.name, :length => 50) %></span>
	  <p><%= truncate(product.description, :length => 100) %><a href="#"><img src="/assets/right_arrow.jpg" alt="" width="16" height="15" border="0" align="absmiddle" style="margin-top:" /></a></p></div>
     <div class="form_wrap">
     	<table width="100%" border="0" cellpadding="0" cellspacing="10">

     	
      <% if product.price %>
      <div data-hook="product_price" class="columns five <% if !product.has_variants? %> alpha <% else %> omega <% end %>">
        
 
        <div class="add-to-cart">
          <% if product.has_stock? || Spree::Config[:allow_backorders] %>      
            <%= hidden_field_tag (product.has_variants? ? :quantity : "variants[#{product.master.id}]"),
              1, :class => 'title', :in => 1..product.on_hand %>
             
            <tr>
    <td align="center" valign="middle" class="price"> <%= number_to_currency product.price %>  </td>
  </tr>
  	
      <% if product.ad_hoc_option_types && !product.ad_hoc_option_types.empty? %>
      <% lookup=ActionView::LookupContext.new(ActionController::Base.view_paths, {:formats => [:html]}) %>

	<div id="ad_hoc_options" class="textfield_bg1">
  
    <% product.ad_hoc_option_types.each do |ahot| %>
   
      <% ot=ahot.option_type %>
      <% class_str='ad-hoc-option-select' %>
      <% class_str += ' required' if ahot.is_required %>
      <% class_str += ' ad_hoc' if !product.ad_hoc_variant_exclusions.empty? %>

      <%# render a custom partial based on the option type name? %>

      <% partial_name = "spree/products/ad_hoc_options/#{ot.name.gsub(/(-)|(\s)/,"_").downcase}" %>
      <% if lookup.exists?(partial_name,nil,true) %>
        <%= render :partial => partial_name, :locals => {:option_type=>ahot, :class_str=>class_str} %>
      <% else %>
        
        <% select_opts = {:class => class_str} %>
        <% select_opts[:prompt] =  ot.presentation if ahot.option_values.size > 1 %>

       
          <%= select_tag "ad_hoc_option_values[#{ahot.id}]",
            options_for_select(ad_hoc_option_value_options(ahot.option_values)),
            select_opts
            %>
            <br/><br/>
  
      <% end %>
      <% end %> 
      
      
  
</div>
 <% else %>
<div class="textfield_bg" style="background-color: white;height: 100px;">

</div>
<% end %> 

            <tr>
    		<td align="right" valign="top">
    		<% if Spree::Product.count > 1%>
          <input type="submit" class="cart_button" value="" >
          <% else %>
		<input type="submit" class="cart_button1" value="" >
		<% end %>
          <% else %>
            <%= content_tag('strong', t(:out_of_stock)) %>
          <% end %>
        </div>

      </div>
    <% end %> 
    
    


 
  </td>
    </tr>
</table>
 </td>
		
</div></tr>
</table><% end %></div></div>


	
<% end %>

<% end %>

<% if paginated_products.respond_to?(:num_pages)
      params.delete(:search)
      params.delete(:taxon)
%><%= paginate paginated_products %><% end %>
</div>
<%= render 'spree/footer'%>
</div> </div> 
</body>